name: Build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model:
          - Shelly1
          - Shelly1L
          - Shelly1PM
          - Shelly25
          - Shelly2
          - ShellyI3
          - ShellyPlug
          - ShellyPlugS
          - ShellyPlus1
          - ShellyPlus1PM
          - ShellyRGBW2
    name: Build ${{ matrix.model }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install mos build tool
        run: |
          sudo add-apt-repository -y ppa:mongoose-os/mos
          sudo apt -q install -y mos-latest
      - name: Build project
        run: make ${{ matrix.model }} CLEAN=1 RELEASE=1 RELEASE_SUFFIX=$(.github/version.py --suffix)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.model }}
          path: |
            releases/*
            !releases/**/elf
          if-no-files-found: error
