name: Check format
on:
  push:
  pull_request:
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check formatting
        run: make check-format
